language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28

before_install:
- chmod +x gradlew

stages:
- name: build
- name: coverage-report
- name: sign-apk
  if: branch = master
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: build
    script:
    - ./gradlew build
  - stage: coverage-report
    script:
    - ./gradlew jacocoTestReport
    - bash <(curl -s https://codecov.io/bash)
  - stage: sign-apk
    before_script:
    - openssl aes-256-cbc -K $encrypted_c3eed0a2d6e5_key -iv $encrypted_c3eed0a2d6e5_iv
      -in somestuff.tar.enc -out somestuff.tar -d
    - tar -xvf somestuff.tar
    script:
    - ./gradlew assembleRelease
  - stage: deploy
    script:
    - ./gradlew publishReleaseApk
